### ISSUE TITLE
Menu works with 1 radio channel but not with multiple

### ISSUE THREAD

**Issue by CSTMChristina** [GameMaster2030/TokoRadioMenu#1]
Using the sample code from your example for multiple radios and matching the names of the channels in TokoVOIP, the menu will not open. If i remove all but 1 of the radios, regardless of which one it is, and match that name on TokoVOIP, the menu then works.

**Comment by TheCodingDutchman** [comment]
Hmm, will look at that. I havent tried multiple channels yet, so I'll see if I can fix that.

**Comment by TheCodingDutchman** [comment]
Have issued a fix for it in v1.1, it should work now. Let me know if it still gives issues.
